-- 테이블 이름 변경
-- RENAME 기존테이블명 TO 기존테이블명_old;
DROP TABLE CUSTOMERS;
DROP TABLE MOVIES;
DROP TABLE THEATERS;
DROP TABLE RESERVATIONS;

--고객
CREATE TABLE customers(
	customer_id 	NUMBER(10) PRIMARY KEY,  		--고객ID
	customer_name varchar2(30),								--고객명
	contact 			char(13),										--연락처
	email					varchar2(50),								--이메일
	reward_points	NUMBER	DEFAULT 0 NOT NULL  --적립포인트
);
--영화
CREATE TABLE movies(
	movie_id			NUMBER(10) PRIMARY KEY,		--영화ID
	title					varchar2(100) NOT NULL,	  --제목
	director			varchar2(30), 						--감독
	genre					varchar2(30), 						--장르
	duration			NUMBER(3), 								--상영시간(총 상영시간, ex) 130분), 
	release_date	DATE											--개봉일
);
--극장
CREATE TABLE theaters(
	theater_id		NUMBER(10) PRIMARY KEY,						--극장ID 
	theater_name	varchar2(100),										--극장명 
	location			varchar2(100),										--위치
	capacity			NUMBER(3)	check(capacity BETWEEN 0 AND 300)	-- 수용인원
);
--예약
CREATE TABLE reservations(
	reservation_id	 NUMBER(10),	--예약ID
	customer_id			 NUMBER(10),	--고객ID
	movie_id				 number(10),  --영화ID
	theater_id			 number(10),	--극장ID
	reservation_date DATE,				--예약일
	showtime				 NUMBER(4),		--상영시간(시작시간 ex)2430)
	seat						 varchar2(10),-- 좌석
	PRIMARY KEY (reservation_id),
	FOREIGN KEY (customer_id) REFERENCES customers(customer_id),
	FOREIGN KEY (movie_id) 		REFERENCES movies(movie_id),
	FOREIGN KEY (theater_id) 	REFERENCES theaters(theater_id)
);

-- 시퀀스 삭제
DROP SEQUENCE CUSTOMERS_CUSTOMER_ID_SEQ;
DROP SEQUENCE MOVIES_MOVIE_ID_SEQ;
DROP SEQUENCE THEATERS_THEATER_ID_SEQ;
DROP SEQUENCE RESERVATIONS_RESERVATION_ID_SEQ;

-- 시퀀스 생성
CREATE SEQUENCE CUSTOMERS_CUSTOMER_ID_SEQ;
CREATE SEQUENCE MOVIES_MOVIE_ID_SEQ;
CREATE SEQUENCE THEATERS_THEATER_ID_SEQ;
CREATE SEQUENCE RESERVATIONS_RESERVATION_ID_SEQ;

--고객
SELECT * FROM CUSTOMERS;
DELETE FROM CUSTOMERS;
COMMIT;
INSERT INTO customers (customer_id,customer_name,contact,email)
		 VALUES (CUSTOMERS_CUSTOMER_ID_SEQ.NEXTVAL, '홍길동1','010-1234-1111','hong1@example.com');
INSERT INTO customers (customer_id,customer_name,contact,email)
		 VALUES (CUSTOMERS_CUSTOMER_ID_SEQ.NEXTVAL, '홍길동2','010-1234-2222','hong2@example.com');
INSERT INTO customers (customer_id,customer_name,contact,email)
		 VALUES (CUSTOMERS_CUSTOMER_ID_SEQ.NEXTVAL, '홍길동3','010-1234-3333','hong3@example.com');
INSERT INTO customers (customer_id,customer_name,contact,email)
		 VALUES (CUSTOMERS_CUSTOMER_ID_SEQ.NEXTVAL, '홍길동4','010-1234-4444','hong4@example.com');
INSERT INTO customers (customer_id,customer_name,contact,email)
		 VALUES (CUSTOMERS_CUSTOMER_ID_SEQ.NEXTVAL, '홍길동5','010-1234-5555','hong5@example.com');
ROLLBACK;
COMMIT;

--영화
SELECT * FROM MOVIES;
DELETE FROM MOVIES;
COMMIT;
INSERT INTO MOVIES 
		 VALUES (MOVIES_MOVIE_ID_SEQ.nextval,'제목1','감독1','장르1',110,to_date('2025-01-01','YYYY-MM-DD'));
INSERT INTO MOVIES 
		 VALUES (MOVIES_MOVIE_ID_SEQ.nextval,'제목2','감독2','장르2',120,to_date('2025-01-02','YYYY-MM-DD'));
INSERT INTO MOVIES 
		 VALUES (MOVIES_MOVIE_ID_SEQ.nextval,'제목3','감독3','장르3',130,to_date('2025-01-03','YYYY-MM-DD'));
INSERT INTO MOVIES 
		 VALUES (MOVIES_MOVIE_ID_SEQ.nextval,'제목4','감독4','장르4',140,to_date('2025-01-04','YYYY-MM-DD'));
INSERT INTO MOVIES 
		 VALUES (MOVIES_MOVIE_ID_SEQ.nextval,'제목5','감독5','장르5',150,to_date('2025-01-05','YYYY-MM-DD'));
ROLLBACK;

--극장
SELECT * FROM THEATERS;
INSERT INTO THEATERS 
		 VALUES (THEATERS_THEATER_ID_SEQ.NEXTVAL,'극장명1','위치1',100);
INSERT INTO THEATERS 
		 VALUES (THEATERS_THEATER_ID_SEQ.NEXTVAL,'극장명2','위치2',200);
INSERT INTO THEATERS 
		 VALUES (THEATERS_THEATER_ID_SEQ.NEXTVAL,'극장명3','위치3',200);
INSERT INTO THEATERS 
		 VALUES (THEATERS_THEATER_ID_SEQ.NEXTVAL,'극장명4','위치4',300);
INSERT INTO THEATERS 
		 VALUES (THEATERS_THEATER_ID_SEQ.NEXTVAL,'극장명5','위치5',300);


--예약
SELECT * FROM RESERVATIONS;
DELETE FROM RESERVATIONS;
COMMIT;
INSERT INTO RESERVATIONS 
		 VALUES(RESERVATIONS_RESERVATION_ID_SEQ.NEXTVAL,1,1,1,TO_DATE('2024-12-24','YYYY-MM-DD'),1300,'A1');
INSERT INTO RESERVATIONS 
		 VALUES(RESERVATIONS_RESERVATION_ID_SEQ.NEXTVAL,2,1,1,TO_DATE('2024-12-24','YYYY-MM-DD'),1400,'B1');
INSERT INTO RESERVATIONS 
		 VALUES(RESERVATIONS_RESERVATION_ID_SEQ.NEXTVAL,3,2,2,TO_DATE('2024-12-24','YYYY-MM-DD'),1500,'C1');
INSERT INTO RESERVATIONS 
		 VALUES(RESERVATIONS_RESERVATION_ID_SEQ.NEXTVAL,4,2,2,TO_DATE('2024-12-24','YYYY-MM-DD'),1600,'D1');
INSERT INTO RESERVATIONS 
		 VALUES(RESERVATIONS_RESERVATION_ID_SEQ.NEXTVAL,5,2,2,TO_DATE('2024-12-24','YYYY-MM-DD'),1700,'E1');
COMMIT;

--1 영화 테이블의 개봉일 컬럼 사용해 현재 상영 중인 영화를 찾는 쿼리문
SELECT TITLE "현재 상영 중인 영화" FROM MOVIES 
WHERE RELEASE_date <= sysdate;

--2 극장 테이블에서 특정 위치의 극장 찾고 해당 극장에서 상영하는 영화 목록 쿼리문
SELECT THEATER_NAME "극장명", TITLE "상영 중인 영화" 
FROM THEATERS T
INNER JOIN RESERVATIONS R ON T.THEATER_ID = R.THEATER_ID
INNER JOIN MOVIES M ON M.MOVIE_ID = R.MOVIE_ID
WHERE T.LOCATION = '위치1' OR T.LOCATION = '위치2';

--3 예약 테이블 사용해 특정 고객의 예약 내역, 예약한 영화 정보 찾는 쿼리문
SELECT C.CUSTOMER_NAME "고객명", R.RESERVATION_DATE "예약일", M.TITLE "예약한 영화"
FROM CUSTOMERS C
INNER JOIN RESERVATIONS R ON C.CUSTOMER_ID = R.CUSTOMER_ID
INNER JOIN MOVIES M ON M.MOVIE_ID = R.MOVIE_ID
WHERE C.CUSTOMER_NAME = '홍길동1';

--4 예약과 극장 조인해 각 극장별 예약된 좌석 수 계산 쿼리문
SELECT T.THEATER_NAME "극장 명", COUNT(R.SEAT) "예약된 좌석 수"
FROM THEATERS T
INNER JOIN RESERVATIONS R ON T.THEATER_ID = R.THEATER_ID
GROUP BY T.THEATER_NAME;

--5 가장 인기 있는 영화 장르를 찾는 쿼리문 (예약 수 기준)
SELECT GENRE "가장 인기있는 장르"
FROM (
    SELECT M.GENRE, COUNT(*) CNT
    FROM MOVIES M
    INNER JOIN RESERVATIONS R ON M.MOVIE_ID = R.MOVIE_ID
    GROUP BY M.GENRE
    ORDER BY CNT DESC
)
WHERE ROWNUM = 1;

-- 예약 한 건도 없는 영화 제목
SELECT M.TITLE "영화 제목"
FROM MOVIES M
LEFT JOIN RESERVATIONS R ON M.MOVIE_ID = R.MOVIE_ID
WHERE R.MOVIE_ID IS NULL;

--차집합
SELECT M.TITLE
FROM MOVIES M
MINUS
SELECT M.TITLE
FROM MOVIES M
WHERE EXISTS ( SELECT *
				FROM RESERVATIONS R
				WHERE R.MOVIE_ID = M.MOVIE_ID);

-- 예약 한 번도 하지 않은 고객명
--INNER 조인
SELECT C.CUSTOMER_NAME
FROM CUSTOMERS C
WHERE NOT EXISTS (
  SELECT *
  FROM RESERVATIONS R
  WHERE R.CUSTOMER_ID = C.CUSTOMER_ID
); 

--OUTER 조인
SELECT C.CUSTOMER_NAME  "고객명"
FROM CUSTOMERS C
LEFT JOIN RESERVATIONS R ON C.CUSTOMER_ID = R.CUSTOMER_ID
WHERE R.CUSTOMER_ID IS NULL;

--차집합
SELECT C.CUSTOMER_NAME
FROM CUSTOMERS C
MINUS
SELECT C.CUSTOMER_NAME
FROM CUSTOMERS C
WHERE EXISTS ( SELECT *
				FROM RESERVATIONS R
				WHERE R.CUSTOMER_ID = C.CUSTOMER_ID);